### ISSUE TITLE
Formatting with syntax errors replaces the buffer

### ISSUE THREAD

**Issue by richerve** [tminor/jsonnet-mode#11]
When running `jsonnet-reformat-buffer` if there's an error the whole buffer is replaced by the output of the `fmt` command. In that case an undo will give you back the buffer content but it would be better if checking first if there's an error and in that case log to the `*jsonnet*` buffer, if not reformat in place.

**Comment by seh** [comment]
I have a local patch that accomplishes this goal. I've been using it for several months, to good effect. I can post a PR if the maintainers agree that this behavior would be better.

**Comment by richerve** [comment]
Hi @seh, 

Can you post the path here too in case the PR takes more time? I'm just starting with elisp so probably can't contribute as right now. Thank you

**Comment by nfelt** [comment]
+1, I also encountered this issue.  @seh it would be great to see your patch!

**Comment by seh** [comment]
Please see #12.

I encourage you to evaluate the patched definitions and try using the three modified commands—`jsonnet-eval-buffer`, `jsonnet-reformat-buffer`, and `jsonnet-jump-to-definition`—for a few days to see how you like it.

**Comment by nfelt** [comment]
Thanks for putting up the PR @seh - it's working great for me and a definite improvement over the previous behavior.  I noticed in addition to the better syntax error handling, it also preserves the cursor position and shows a nice message when formatting is a no-op so you know it still worked :)

The one issue I had was that in my emacs 26.1 I initially got the error `Symbol’s function definition is void: when-let` when trying to trigger formatting.  Based on some googling I fixed this by just adding `(require 'subr-x)` at the top of the file.

**Comment by seh** [comment]
I'm glad to hear it's working well, @nfelt. Per your finding, I just pushed an update to #12 (2ecc1eff8c6cbc61a40246abda7b7fe05eba46e1) that adds the dependency of _subr-x_, which I must have been pulling in from some other configuration I have loaded. I also eliminated a spurious toggling of the buffer's read-only state, left over from before I was allowing checking the formatting of a read-only buffer.

**Comment by richerve** [comment]
@mgyucht any update on working/merging @seh's patch in the linked issue?

**Comment by seh** [comment]
Note too that I have[ another branch sitting on top of that one](https://github.com/seh/jsonnet-mode/tree/handle-separate-format-tool)—in particular, commit seh/jsonnet-mode@55f3195a3ef5a53a0a8a4bdae8540a3c37ff8b9d—that accommodates the split _jsonnet_ and _jsonnetfmt_ tools that we find as of Jsonnet version 0.13.0.

I haven't requested merging that here because #12 has been sitting open for five months now. As it's been eight and a half months since the last commit to the "master" branch, perhaps this repository should be archived.
