### ISSUE TITLE
How to specify external variable and use the mode for qbec

### ISSUE THREAD

**Issue by Andor** [tminor/jsonnet-mode#22]
I am trying to use this mode for [qbec](https://qbec.io/) files, which contains custom external variable:
```
local env = std.extVar('qbec.io/env');
```

And I got the error in `*Messages*`:
```
undefined external variable: qbec.io/env
```

I tried to customize jsonnet command with this:
```
 (jsonnet-command "jsonnet --ext-str qbec.io/env=testenv")
```
But it didn't help.

Could you please help me to understand what exactly is wrong here?

UPD: apparently that error comes from flycheck, not from `jsonnet-mode`, but:
When I call `jsonnet-eval-function` it returns:
```
apply: Searching for program: No such file or directory, jsonnet --ext-str qbec.io/env=testenv
```

**Comment by tminor** [comment]
This is an idiosyncrasy of `call-process` which requires a command string as its first argument and a list of strings as its fifth argument (`ARGS`). I can think of a few possible ways to solve this:

1. "Parse" additional options/flags from `jsonnet-command` (I'm not really a fan of this approach).
2. Add a new `defcustom` for additional `jsonnet-command` flags/options (this seems okay).
3. Add a new `defcustom` for external variables, possibly an `alist` like this:

```elisp
'(("var" . "val"))
```

I prefer the third option, but it would require additional variables for `--ext-str-file`, `--ext-code`, etc. I can probably do this tomorrow or over the weekend.

**Comment by Andor** [comment]
@tminor I suppose you can try to replace `call-process` with `call-process-shell-command`, which should handle everything by itself.

**Comment by tminor** [comment]
> Or maybe add some dumb "heuristic": if command contain any space, then run it with call-process-shell-command, otherwise use simple call-process.

That's sort of what I meant by

> "Parse" additional options/flags from jsonnet-command

It's seems like an okay option, but I'd prefer a separate variable (options 2 and 3). If the heuristic is as dumb as me, I wouldn't trust it :)

**Comment by tminor** [comment]
Let me know if e93a1f55e5f9bc2b34b025c6f7a60a6f159268d1 works for you @Andor!
