### ISSUE TITLE
Formatting/Indent is messed when using the * (asterisk) character in config file

### ISSUE THREAD

**Issue by vikigenius** [tminor/jsonnet-mode#26]
Consider the following snippet

```
local data_base_path = 'path/to/data/';
{
    "data_pattern": data_base_path + "*.tsv"
    "key1": "value1",
    "key2": "value2",
}
```

Indenting the region messes up all lines after the line containing the asterisk.

**Comment by tminor** [comment]
Perhaps it's because of the missing comma at the end of the line containing the `*`. In any case, I'm not able to replicate the issue with `emacs -q`. What version of `jsonnet-mode` are you using (you should be able to find it via `package-list-packages`, I think)?

**Comment by vikigenius** [comment]
Ah, actually that was a mistake, the error happens even with the comma. I am actually using the master directly. I use straight to manage my packages.

**Comment by tminor** [comment]
How are you indenting the region? Are you using `indent-region` or something else? Are you able to replicate the issue with `emacs -q`? (FWIW, I added a test case locally using the snippet you provided and the new test passed.)

**Comment by vikigenius** [comment]
There was a slight change. Try this snippet, I could reproduce from it.

```
local data_base_path = 'path/to/data/';
{
  "data_pattern": data_base_path + "train/*.tsv",
  "key1": "value1",
  "key2": "value2",
}
```

indent-region is what is causing the error.

**Comment by tminor** [comment]
Ah, that does it for me, too. Thanks! I'll take a closer look and will hopefully have a fix soon.

**Comment by tminor** [comment]
Oh, I forgot: indentation via SMIE isn't enabled by default. Try setting `jsonnet-use-smie` to `t`. `indent-region` works for me with SMIE enabled. I'll probably remove the old indentation function implementation soon.

**Comment by vikigenius** [comment]
Yes, setting `jsonnet-use-smie` fixed the issue, thanks.
